# Custom Language File for Launcher Customizer

[ejs.app]
title = "YakPixel Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO YAKPIXEL LAUNCHER"
welcomeDescription = "Our goal is to make loading mods easier for new players, with a 1 click install and all your mods preconfigured! Although we don't support cheaters, we have provided a few profiles designed for macroers, although remember to use it at your own risk!"
welcomeDescCTA = "You are just a few clicks away from Hypixel."
